# Generated by Django 3.0 on 2022-02-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20220211_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='information',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
