# Generated by Django 3.0 on 2022-03-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20220213_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packeage_name', models.CharField(max_length=100)),
                ('zip_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['rank']},
        ),
    ]
